version: '3.8'

services:
  frontend:
    build: ./front
    ports:
      - "80:80"
    networks:
      - app-network

  backend:
    build: ./back
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:

